services:
  api:
    build: .
    container_name: sci_api
    ports:
      - "8000:8000"
    environment:
      # - REDIS_URI=redis://redis:6379/0
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_EXPERIMENT_NAME=production_physics
    depends_on:
      redis:
        condition: service_healthy
      mlflow:
        condition: service_started
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sci_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.17.0
    container_name: sci_mlflow
    ports:
      - "5000:5000"
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri sqlite:///mlflow.db 
      --default-artifact-root ./mlflow-artifacts
    volumes:
      - mlflow_data:/mlflow
    restart: unless-stopped

volumes:
  mlflow_data: